spring.application.name=expense-tracker
# MySQL Connection Settings(finds the db, username is root with no password)
spring.datasource.url=jdbc:mysql://localhost:3306/expense_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (Automatically creates table in xampp each time i create a class)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#show-sql=shows the sql queries automatically written